### ISSUE TITLE
Animación de objeto en 3D Blender

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo_cafe-huerto-el-mamey#1]
[Animación de objeto en 3D Blender.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-objeto-3d-en-blender-con-animacion-equipo_cafe-huerto-el-mamey/files/8337302/Animacion.de.objeto.en.3D.Blender.pdf)

**Comment by EMMANUELRHZ** [comment]
La aplicación se ejecuta correctamente y se muestra un buen diseño y modelado de su objeto en 3d.

CALIF=20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
